### ISSUE TITLE
Database rewrite

### ISSUE THREAD

**Issue by Blumster** [InfiniteRasa/Rasa.NET#4]
Entity Framework
Store the data in memory, occasionally saving them to the DB

**Comment by damuras** [comment]
How will this affect the memory requirements of the server?

**Comment by Blumster** [comment]
It will increase, but if a character is logged in, we have to have that character's data loaded in the memory anyways, this enhancement is about the saving method. Periodically saving the players takes off load, but there can be data loss if the server crashes. The players could be saved while the main loop sleeps, or on another thread.
